# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerName', models.CharField(max_length=50)),
                ('Level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resources', models.IntegerField()),
                ('Soldiers', models.IntegerField()),
                ('Player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Money', models.IntegerField()),
                ('BarrackName', models.CharField(max_length=50)),
                ('Town_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
            ],
        ),
    ]
